In [1]:
import numpy as np

In [ ]:
#  one dimension

array1 = np.array([1,2,3,4,5])
array1

array([1, 2, 3, 4, 5])

In [3]:
# two dimensions
array2 = np.array([[1,2], [3,4]])
array2

array([[1, 2],
       [3, 4]])

In [4]:
array2.shape

(2, 2)

In [ ]:
# 2x2 array with random floats


In [5]:
np.random.rand(2,2)

array([[0.82120233, 0.45088079],
       [0.8858772 , 0.15155445]])

In [6]:
# fill out the 3x4 array with 8s
np.full((3,4), 8)

array([[8, 8, 8, 8],
       [8, 8, 8, 8],
       [8, 8, 8, 8]])

In [8]:
# fill out the array with ones
np.ones((3,3))

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

In [9]:
# fill out with zeros
np.zeros((2,2))

array([[0., 0.],
       [0., 0.]])

In [10]:
# simple sequence from 0 to 4
np.arange(0,4)

array([0, 1, 2, 3])

In [11]:
# simple sequence from 0 to 30 with 3 steps
np.arange(0,30, 3)

array([ 0,  3,  6,  9, 12, 15, 18, 21, 24, 27])

In [12]:
# some math operations on arrays
array3 =np.array([10,20,30,40,50,60,70,80,90,100])
array3/10

array([ 1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10.])

In [13]:
# reshaping arrays
array4 = np.ones((3,4))
array4

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [14]:
array4.reshape((2,6))

array([[1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1.]])

In [15]:
# error when the number of items do not match
array4.reshape((1,6))

ValueError: cannot reshape array of size 12 into shape (1,6)

In [16]:
# flattening arrays
print(array4)

[[1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]]


In [17]:
print(array4.flatten())

[1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]


In [18]:
#  expanding arrays

array5 = np.ones((3,4))
print(array5)

expanded = array5[np.newaxis, :]
print(expanded)

[[1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]]
[[[1. 1. 1. 1.]
  [1. 1. 1. 1.]
  [1. 1. 1. 1.]]]


In [20]:
print(array5.shape)
print(expanded.shape)

(3, 4)
(1, 3, 4)


In [21]:
# conditions
array6  = np.array([[2,3,4],[3,5,6]])
array6<5

array([[ True,  True,  True],
       [ True, False, False]])

In [22]:

array6[array6<5]

array([2, 3, 4, 3])

In [23]:
# slicing
array7 =np.array([1,2,3,4,5,6,7,8,9,10])
array7[1:4]

array([2, 3, 4])

In [24]:
array7[-1:]

array([10])

In [25]:
array7[:-1]

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [29]:
# horizontally stacking
first= np.full((2,3),3)
print(first)
second = np.full((2,4),5)
print(second)
np.hstack([first, second])

[[3 3 3]
 [3 3 3]]
[[5 5 5 5]
 [5 5 5 5]]


array([[3, 3, 3, 5, 5, 5, 5],
       [3, 3, 3, 5, 5, 5, 5]])

In [30]:
# vertical stacking
third = np.full((3,3), 1)
forth = np.full((3,3), 2)
np.vstack((third, forth))

array([[1, 1, 1],
       [1, 1, 1],
       [1, 1, 1],
       [2, 2, 2],
       [2, 2, 2],
       [2, 2, 2]])

In [33]:
# splitting arrays
np.hsplit(second, 2)

[array([[5, 5],
        [5, 5]]),
 array([[5, 5],
        [5, 5]])]

In [36]:
# unpacking
first, second = np.hsplit(second,2)
print(first)
print(second)

[[5]
 [5]]
[[5]
 [5]]
